name = "family-talk"
main = "dist/server/index.js"
compatibility_date = "2026-05-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "family-talk"
database_id = "68e170c8-faeb-4012-9494-d6fa538069af"
migrations_dir = "drizzle"
